site_name: Kladde
site_url: https://kladde.uni-jena.de/
theme:
  name: material

plugins:
  - search
  - redirects:
      redirect_maps:
        how-to-start.md: new-entry.md
        chemicaleditor.md: adding-chemical-equation.md
        scheme.md: snippets.md

markdown_extensions:
  - footnotes
  - md_in_html

nav:
  - Welcome: index.md
  - About:
      - What is ELN?: eln.md
      - Meet our team:
          - Prof. Dr. Christoph Steinbeck: christoph.md
          - Dr. Kevin Maik Jablonka: kevin.md
          - Dr. Kohulan Rajan: kohulan.md
          - Soyee Chan: soyee.md
      - License: license.md
  - How to start:
      - New Entry: new-entry.md
      - Adding chemical equation: adding-chemical-equation.md
      - Snippets: snippets.md # steps of experiments
  - Analysis:
      - Sample Analysis: sample-analysis.md
      - IR: ir.md
      - NMR: nmr.md
      - MS: ms.md
  - Report: report.md

extra_javascript:
  - javascripts/extra.js
